services:
  frontend:
    build:
      context: ./react-router-ssr
      dockerfile: Dockerfile
    container_name: hackforge_frontend
    expose:
      - "3000"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8080/api

  backend:
    build:
      context: ./backend
    container_name: hackforge_backend
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    expose:
      - "8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:18-alpine
    container_name: hackforge_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./out/postgres:/var/lib/postgresql

  migrator:
    container_name: hackforge_migrator
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations


  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
